---
apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: lsd-llama-milvus
spec:
  replicas: 1
  server:
    containerSpec:
      resources:
        requests:
          cpu: "250m"
          memory: "500Mi"
        limits:
          cpu: "2"
          memory: "12Gi"
      env:
        - name: INFERENCE_MODEL
          value: vllm
        - name: VLLM_URL
          value: http://vllm-predictor:8080/v1
        - name: MILVUS_DB_PATH
          value: /.llama/distributions/remote-vllm/milvus.db
      name: llama-stack
      port: 8321
    distribution:
      name: rh-dev
    podOverrides:
      volumeMounts:
        - mountPath: /opt/app-root/src/.llama
          name: llama-storage
      volumes:
        - emptyDir: {}
          name: llama-storage
