apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kokoro-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kokoro-fastapi
  labels:
    app: kokoro-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kokoro-fastapi
  template:
    metadata:
      labels:
        app: kokoro-fastapi
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: kokoro-fastapi
        image: ghcr.io/remsky/kokoro-fastapi-cpu:latest
        ports:
        - containerPort: 8880
        env:
        - name: XDG_CACHE_HOME
          value: /cache
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: cache-volume
          mountPath: /cache
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: kokoro-cache-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kokoro-fastapi
spec:
  selector:
    app: kokoro-fastapi
  ports:
    - protocol: TCP
      port: 8880
      targetPort: 8880
  type: ClusterIP
