apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: redbank-lsd
spec:
  replicas: 1
  server:
    containerSpec:
      env:
        - name: INFERENCE_MODEL
          value: qwen2-5
        - name: VLLM_URL
          value: 'http://qwen2-5-predictor:80/v1'
        - name: MILVUS_DB_PATH
          value: /.llama/distributions/remote-vllm/milvus.db
      name: llama-stack
      port: 8321
    distribution:
      name: 'rh-dev'
    podOverrides:
      volumeMounts:
        - mountPath: /root/.llama
          name: llama-storage
      volumes:
        - emptyDir: {}
          name: llama-storage
